##############################################################################
#  CloudPulse – Kubernetes Namespaces
#  bodhganga : application workloads (backend + frontend + mongodb)
##############################################################################
apiVersion: v1
kind: Namespace
metadata:
  name: bodhganga
  labels:
    app.kubernetes.io/managed-by: cloudpulse
    environment: production
    monitoring: "true"
