apiVersion: v1
kind: Secret
metadata:
  name: bodhganga-secrets
  namespace: bodhganga
  labels:
    app.kubernetes.io/name: bodhganga
    app.kubernetes.io/part-of: cloudpulse
type: Opaque
data:
  mongo-root-user: YWRtaW4=
  mongo-root-pass: Q0hBTkdFX1RISVNfU1RST05HX1BBU1NXT1JE
  mongo-uri: bW9uZ29kYjovL2FkbWluOkNIQU5HRV9USElTX1NUUk9OR19QQVNTV09SREBib2RoZ2FuZ2EtbW9uZ29kYjoyNzAxNy9ib2RoZ2FuZ2E/YXV0aFNvdXJjZT1hZG1pbg==
  jwt-secret: UkVQTEFDRV9XSVRIX1NUUk9OR182NF9DSEFSX1NFQ1JFVF9rZXk=
  aws-access-key-id: QUNLSUFJT1NGT0ROTjdFWEFNUExF
  aws-secret-access-key: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==
  razorpay-key-id: ""
  razorpay-key-secret: ""
  smtp-user: ""
  smtp-pass: ""
  gemini-api-key: ""
  google-credentials-json: ""
