apiVersion: v1
kind: Service
metadata:
  name: bodhganga-backend-svc
  namespace: bodhganga
  labels:
    app.kubernetes.io/name: bodhganga-backend
    app.kubernetes.io/part-of: cloudpulse
    app.kubernetes.io/component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bodhganga-backend
  ports:
    - name: app
      port: 9090
      targetPort: 9090
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: bodhganga-frontend-svc
  namespace: bodhganga
  labels:
    app.kubernetes.io/name: bodhganga-frontend
    app.kubernetes.io/part-of: cloudpulse
    app.kubernetes.io/component: frontend
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: bodhganga-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: bodhganga-mongodb
  namespace: bodhganga
  labels:
    app.kubernetes.io/name: bodhganga-mongodb
    app.kubernetes.io/part-of: cloudpulse
    app.kubernetes.io/component: database
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: bodhganga-mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bodhganga-backend-pdb
  namespace: bodhganga
  labels:
    app.kubernetes.io/name: bodhganga-backend
    app.kubernetes.io/part-of: cloudpulse
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: bodhganga-backend

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bodhganga-frontend-pdb
  namespace: bodhganga
  labels:
    app.kubernetes.io/name: bodhganga-frontend
    app.kubernetes.io/part-of: cloudpulse
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bodhganga-frontend
