use bodhganga;
db.states.insertMany([
    {"_id": "andhra-pradesh", "name": "Andhra Pradesh", "code": "AP", "capital": "Amaravati", "description": "Comprehensive preparation material", "type": "STATE", "status": "ACTIVE", "notesCount": 245, "questionsCount": 1850},
    {"_id": "arunachal-pradesh", "name": "Arunachal Pradesh", "code": "AR", "capital": "Itanagar", "description": "Study materials", "type": "STATE", "status": "ACTIVE"},
    {"_id": "assam", "name": "Assam", "code": "AS", "capital": "Dispur", "description": "Complete study resource", "type": "STATE", "status": "ACTIVE"},
    {"_id": "bihar", "name": "Bihar", "code": "BR", "capital": "Patna", "description": "Extensive preparation material", "type": "STATE", "status": "ACTIVE"},
    {"_id": "chhattisgarh", "name": "Chhattisgarh", "code": "CT", "capital": "Raipur", "description": "Comprehensive notes", "type": "STATE", "status": "ACTIVE"},
    {"_id": "goa", "name": "Goa", "code": "GA", "capital": "Panaji", "description": "Study materials", "type": "STATE", "status": "ACTIVE"},
    {"_id": "gujarat", "name": "Gujarat", "code": "GJ", "capital": "Gandhinagar", "description": "Complete resource", "type": "STATE", "status": "ACTIVE"},
    {"_id": "haryana", "name": "Haryana", "code": "HR", "capital": "Chandigarh", "description": "Preparation material", "type": "STATE", "status": "ACTIVE"},
    {"_id": "himachal-pradesh", "name": "Himachal Pradesh", "code": "HP", "capital": "Shimla", "description": "Study materials", "type": "STATE", "status": "ACTIVE"},
    {"_id": "jharkhand", "name": "Jharkhand", "code": "JH", "capital": "Ranchi", "description": "Comprehensive notes", "type": "STATE", "status": "ACTIVE"},
    {"_id": "karnataka", "name": "Karnataka", "code": "KA", "capital": "Bengaluru", "description": "Extensive study resource", "type": "STATE", "status": "ACTIVE"},
    {"_id": "kerala", "name": "Kerala", "code": "KL", "capital": "Thiruvananthapuram", "description": "Complete preparation material", "type": "STATE", "status": "ACTIVE"},
    {"_id": "madhya-pradesh", "name": "Madhya Pradesh", "code": "MP", "capital": "Bhopal", "description": "Comprehensive resource", "type": "STATE", "status": "ACTIVE"},
    {"_id": "maharashtra", "name": "Maharashtra", "code": "MH", "capital": "Mumbai", "description": "Extensive study materials", "type": "STATE", "status": "ACTIVE"},
    {"_id": "manipur", "name": "Manipur", "code": "MN", "capital": "Imphal", "description": "Study materials", "type": "STATE", "status": "ACTIVE"},
    {"_id": "meghalaya", "name": "Meghalaya", "code": "ML", "capital": "Shillong", "description": "Preparation resource", "type": "STATE", "status": "ACTIVE"},
    {"_id": "mizoram", "name": "Mizoram", "code": "MZ", "capital": "Aizawl", "description": "Study materials", "type": "STATE", "status": "ACTIVE"},
    {"_id": "nagaland", "name": "Nagaland", "code": "NL", "capital": "Kohima", "description": "Comprehensive notes", "type": "STATE", "status": "ACTIVE"},
    {"_id": "odisha", "name": "Odisha", "code": "OR", "capital": "Bhubaneswar", "description": "Complete resource", "type": "STATE", "status": "ACTIVE"},
    {"_id": "punjab", "name": "Punjab", "code": "PB", "capital": "Chandigarh", "description": "Study materials", "type": "STATE", "status": "ACTIVE"},
    {"_id": "rajasthan", "name": "Rajasthan", "code": "RJ", "capital": "Jaipur", "description": "Extensive preparation material", "type": "STATE", "status": "ACTIVE"},
    {"_id": "sikkim", "name": "Sikkim", "code": "SK", "capital": "Gangtok", "description": "Study resource", "type": "STATE", "status": "ACTIVE"},
    {"_id": "tamil-nadu", "name": "Tamil Nadu", "code": "TN", "capital": "Chennai", "description": "Comprehensive resource", "type": "STATE", "status": "ACTIVE"},
    {"_id": "telangana", "name": "Telangana", "code": "TG", "capital": "Hyderabad", "description": "Complete study material", "type": "STATE", "status": "ACTIVE"},
    {"_id": "tripura", "name": "Tripura", "code": "TR", "capital": "Agartala", "description": "Preparation materials", "type": "STATE", "status": "ACTIVE"},
    {"_id": "uttar-pradesh", "name": "Uttar Pradesh", "code": "UP", "capital": "Lucknow", "description": "Extensive study resource", "type": "STATE", "status": "ACTIVE"},
    {"_id": "uttarakhand", "name": "Uttarakhand", "code": "UK", "capital": "Dehradun (Winter)", "description": "Study materials", "type": "STATE", "status": "ACTIVE"},
    {"_id": "west-bengal", "name": "West Bengal", "code": "WB", "capital": "Kolkata", "description": "Comprehensive resource", "type": "STATE", "status": "ACTIVE"},
    
    {"_id": "andaman-and-nicobar", "name": "Andaman and Nicobar Islands", "code": "AN", "capital": "Port Blair", "description": "Study materials", "type": "UT", "status": "ACTIVE"},
    {"_id": "chandigarh", "name": "Chandigarh", "code": "CH", "capital": "Chandigarh", "description": "Study materials", "type": "UT", "status": "ACTIVE"},
    {"_id": "dadra-nagar-haveli", "name": "Dadra and Nagar Haveli and Daman and Diu", "code": "DN", "capital": "Daman", "description": "Study materials", "type": "UT", "status": "ACTIVE"},
    {"_id": "delhi", "name": "Delhi", "code": "DL", "capital": "New Delhi", "description": "Extensive study materials", "type": "UT", "status": "ACTIVE"},
    {"_id": "jammu-kashmir", "name": "Jammu and Kashmir", "code": "JK", "capital": "Srinagar (Summer), Jammu (Winter)", "description": "Comprehensive notes", "type": "UT", "status": "ACTIVE"},
    {"_id": "ladakh", "name": "Ladakh", "code": "LA", "capital": "Leh, Kargil", "description": "Study materials", "type": "UT", "status": "ACTIVE"},
    {"_id": "lakshadweep", "name": "Lakshadweep", "code": "LD", "capital": "Kavaratti", "description": "Study materials", "type": "UT", "status": "ACTIVE"},
    {"_id": "puducherry", "name": "Puducherry", "code": "PY", "capital": "Puducherry", "description": "Study materials", "type": "UT", "status": "ACTIVE"}
]);
print("Inserted 36 states and UTs successfully.");
